### ISSUE TITLE
Pasting via Ctrl+V yields a string prefixed with `^[[200~` characters

### ISSUE THREAD

**Issue by sudomateo** [cs50/labs#34]
Inside a lab environment on https://lab.cs50.io/cs50/labs, using Ctrl+V to paste a string from the clipboard yields a string prefixed with `^[[200~` characters. This does not happen when right clicking and selecting Paste.

Due to this behavior, using Ctrl+V to paste in your GitHub password when prompted by `check50` or `submit50` causes a `Invalid username and/or password.` error to be thrown.

Steps to reproduce:

* Gather a string on your clipboard.
* Open a test file for editing using `vim test.txt`.
* Press the `I` key to enter insert mode.
* Press Ctrl+V to paste the string that's on your clipboard.
* Notice the string is prefixed with `^[[200~`.
* Press the `Enter` key to go to a new line.
* Right click and select Paste to paste the string that's on your clipboard.
* Notice the string is pasted as desired with no `^[[200~` prefix.

Tested with the following specs:
* Windows 10 Pro, Version 1909, OS build 18363.657
* Firefox 73.0.1 (64-bit)

**Comment by curiouskiwi** [comment]
Is this OS specific?  I cannot replicate this on my mac.

**Comment by sudomateo** [comment]
@curiouskiwi I'm not sure. I only tested on Windows 10 with Firefox. I will test on Linux with Firefox now and report my results. I do not have a macOS machine to test with.

**Comment by sudomateo** [comment]
I just tested on Linux using Firefox 73.0.1 (64-bit) and I can still reproduce. I will try using Google Chrome later today.

**Comment by kzidane** [comment]
This seems to be an xterm.js-related issue on Firefox, see https://github.com/xtermjs/xterm.js/issues/292. You should be able to paste using <kbd>Shift</kbd> + <kbd>Ins</kbd> in Firefox for now.

**Comment by sudomateo** [comment]
Thank you @kzidane! I can confirm <kbd>Shift</kbd> + <kbd>Ins</kbd> works on both Linux and Windows with Firefox. I'll go ahead and close this issue.
