### ISSUE TITLE
README.md section shows "404" when README contains an empty {% %} tag

### ISSUE THREAD

**Issue by dektar** [cs50/labs#45]
Example of failure:
README.md: https://github.com/dektar/cspc121-playground/tree/master/cs50lab
Lab version of the same: https://lab.cs50.io/dektar/cspc121-playground/master/cs50lab/

Details:
The README section of the lab.cs50.io shows a "404" error. It would be better to fail elegantly on an empty "{% %}" than return a 404. It took me some time to determine the problem.

Background: 
I was hoping to make a README for a lab that I wanted to make sense in lab.cs50.io AND when read directly in Markdown on GitHub. I had an explanation that users could ignore {% %} if they saw it. However, this caused a 404.

Overall such a cool tool. Thank you!
Note: Not sure if this is the right github repo. Can you help me re-route this bug if not?

**Comment by cbscribe** [comment]
Confirming issue regarding tags. I added a spoiler tag of the form

```
{% spoiler "Hint" %}
You're really not going to like it.
{% endspoiler %}
```

But had a typo in the closing tag: `{% spoiler %}` (ie missing the "end").

Lab sometimes failed to load with a "bad gateway" error, and other times loaded with a 404 in the readme frame. Tricky to troubleshoot in a large document.

**Comment by dmalan** [comment]
Ah, thanks for the reports. Just made a change that should compel the 502 error page to output the actual parsing error. E.g.:

```
Liquid Exception: Liquid syntax error (line 5): Tag '{% %}' was not properly terminated with regexp: /\%\}/ in README.md
```

@dektar, to include "deliberately" invalid tags, do just surround them with `{% raw %}` and `{% endraw %}`!
