### ISSUE TITLE
Small BMP images render extremely blurry in viewer

### ISSUE THREAD

**Issue by dlloyd09** [cs50/labs#9]
See the below, which is an 8x8 pixel BMP

![image](https://user-images.githubusercontent.com/12766040/46030717-ef8e3f00-c0c4-11e8-9e8a-f4db7d47b861.png)

**Comment by dlloyd09** [comment]
Not sure if there's anything we can do to resolve the viewer @dmalan @kzidane  (cc @brianyu28)

**Comment by dmalan** [comment]
@kzidane is this a browser feature that's dithering it, or a Codevolve viewer feature?

**Comment by kzidane** [comment]
@dmalan codevolve. It inherits parent's height and width is always 100%. We could manipulate with CSS or JS but that'd be hackish.

**Comment by coltonoscopy** [comment]
Don't think there's a cleaner fix than this, using CSS:

https://css-tricks.com/almanac/properties/i/image-rendering/

Specifically,

img {
   image-rendering: pixelated;
}

(or however you'd need to do it to just target the image viewer panels)

**Comment by dmalan** [comment]
http://feedback.codevolve.com/feature-requests/p/pixelate-small-images-instead-of-smoothing
